data = read.csv("/home/brendan/Desktop/ass1.csv")
print(data)
lost <- data[which(data$Category=="Lost"),]
print(lost)
gain <- data[which(data$Category=="Gain"),]
print(gain)
long <- data[which(data$Category=="Long"),]
print(long)
longpond <- long[which(long$Sample=="Pond"),]
print(longpond)
longwet <- long[which(long$Sample=="Wetland"),]
print(longwet)
longupa <- long[which(long$Sample=="Upland A"),]
print(longupa)
longupb <- long[which(long$Sample=="Upland B"),]
print(longupb)
gainpond <- gain[which(gain$Sample=="Pond"),]
print(gainpond)
gainwet <- gain[which(gain$Sample=="Wetland"),]
print(gainwet)
gainupa <- gain[which(gain$Sample=="Upland A"),]
print(gainupa)
gainupb <- gain[which(gain$Sample=="Upland B"),]
print(gainupb)
lostpond <- lost[which(lost$Sample=="Pond"),]
print(lostpond)
lostwet <- lost[which(lost$Sample=="Wetland"),]
print(lostwet)
lostupa <- lost[which(lost$Sample=="Upland A"),]
print(lostupa)
lostupb <- lost[which(lost$Sample=="Upland B"),]
print(lostupb)
jpeg('/home/brendan/Desktop/images/bar/longpond.jpg')
barplot(c(mean(longpond$C),mean(longpond$N)),main="Location: Pond, Category: Long",col=c("darkblue","red"),names.arg=c("C","N"),ylim=c(0,12))
dev.off()
jpeg('/home/brendan/Desktop/images/bar/longwet.jpg')
barplot(c(mean(longwet$C),mean(longwet$N)),main="Location: Wetland, Category: Long",col=c("darkblue","red"),names.arg=c("C","N"),ylim=c(0,20))
dev.off()
jpeg('/home/brendan/Desktop/images/bar/longupa.jpg')
barplot(c(mean(longupa$C),mean(longupa$N)),main="Location: Upland A, Category: Long",col=c("darkblue","red"),names.arg=c("C","N"),ylim=c(0,4))
dev.off()
jpeg('/home/brendan/Desktop/images/bar/longupb.jpg')
barplot(c(mean(longupb$C),mean(longupb$N)),main="Location: Upland B, Category: Long",col=c("darkblue","red"),names.arg=c("C","N"),ylim=c(0,4))
dev.off()
jpeg('/home/brendan/Desktop/images/bar/lostpond.jpg')
barplot(c(mean(lostpond$C),mean(lostpond$N)),main="Location: Pond, Category: Lost",col=c("darkblue","red"),names.arg=c("C","N"),ylim=c(0,12))
dev.off()
jpeg('/home/brendan/Desktop/images/bar/lostwet.jpg')
barplot(c(mean(lostwet$C),mean(lostwet$N)),main="Location: Wetland, Category: Lost",col=c("darkblue","red"),names.arg=c("C","N"),ylim=c(0,15))
dev.off()
jpeg('/home/brendan/Desktop/images/bar/lostupa.jpg')
barplot(c(mean(lostupa$C),mean(lostupa$N)),main="Location: Upland A, Category: Lost",col=c("darkblue","red"),names.arg=c("C","N"),ylim=c(0,2))
dev.off()
jpeg('/home/brendan/Desktop/images/bar/lostupb.jpg')
barplot(c(mean(lostupb$C),mean(lostupb$N)),main="Location: Upland B, Category: Lost",col=c("darkblue","red"),names.arg=c("C","N"),ylim=c(0,6))
dev.off()
jpeg('/home/brendan/Desktop/images/bar/gainpond.jpg')
barplot(c(mean(gainpond$C),mean(gainpond$N)),main="Location: Pond, Category: Gain",col=c("darkblue","red"),names.arg=c("C","N"),ylim=c(0,12))
dev.off()
jpeg('/home/brendan/Desktop/images/bar/gainwet.jpg')
barplot(c(mean(gainwet$C),mean(gainwet$N)),main="Location: Wetland, Category: Gain",col=c("darkblue","red"),names.arg=c("C","N"),ylim=c(0,15))
dev.off()
jpeg('/home/brendan/Desktop/images/bar/gainupa.jpg')
barplot(c(mean(gainupa$C),mean(gainupa$N)),main="Location: Upland A, Category: Gain",col=c("darkblue","red"),names.arg=c("C","N"),ylim=c(0,4))
dev.off()
jpeg('/home/brendan/Desktop/images/bar/gainupb.jpg')
barplot(c(mean(gainupb$C),mean(gainupb$N)),main="Location: Upland B, Category: Gain",col=c("darkblue","red"),names.arg=c("C","N"),ylim=c(0,4))
dev.off()
pond <- data[which(data$Sample=="Pond"),]
print(lost)
wet <- data[which(data$Sample=="Wetland"),]
print(wet)
upa <- data[which(data$Sample=="Upland A"),]
print(upa)
upb <- data[which(data$Sample=="Upland B"),]
print(upb)
print("Pond C:")
print(summary(pond$C))
print("Pond N:")
print(summary(pond$N))
print("Wet C:")
print(summary(wet$C))
print("Wet N:")
print(summary(wet$N))
print("Upland A C:")
print(summary(upa$C))
print("Upland A N:")
print(summary(upa$N))
print("Upland B C:")
print(summary(upb$C))
print("Upland B N:")
print(summary(upb$N))
print("Lost C:")
print(summary(lost$C))
print("Lost N:")
print(summary(lost$N))
print("Gain C:")
print(summary(gain$C))
print("Gain N:")
print(summary(gain$N))
print("Long C:")
print(summary(long$C))
print("Long N:")
print(summary(long$N))
print("All C:")
allc <- data$C
print(allc)
print("All N:")
alln <- data$N
print(alln)
print("Gain/pond cor:")
print(cor(gainpond$C,gainpond$N))
gainpondfit <- lm(gainpond$N ~ gainpond$C)
jpeg('/home/brendan/Desktop/images/plot/gainpondplot.jpg')
plot(gainpond$N ~ gainpond$C,xlim=c(0,15),ylim=c(0,10),main="Location: Pond, Category: Gain",xlab="Concentration of C",ylab="Concentration of N")
abline(gainpondfit)
dev.off()
print("Gain/wet cor:")
print(cor(gainwet$C,gainwet$N))
gainwetfit <- lm(gainwet$N ~ gainwet$C)
jpeg('/home/brendan/Desktop/images/plot/gainwetplot.jpg')
plot(gainwet$N ~ gainwet$C,xlim=c(0,15),ylim=c(0,10),main="Location: Wetland, Category: Gain",xlab="Concentration of C",ylab="Concentration of N")
abline(gainwetfit)
dev.off()
print("Gain/upa cor:")
print(cor(gainupa$C,gainupa$N))
gainupafit <- lm(gainupa$N ~ gainupa$C)
jpeg('/home/brendan/Desktop/images/plot/gainupaplot.jpg')
plot(gainupa$N ~ gainupa$C,xlim=c(0,10),ylim=c(0,5),main="Location: Upland A, Category: Gain",xlab="Concentration of C",ylab="Concentration of N")
abline(gainupafit)
dev.off()
print("Gain/upb cor:")
print(cor(gainupb$C,gainupb$N))
gainupbfit <- lm(gainupb$N ~ gainupb$C)
jpeg('/home/brendan/Desktop/images/plot/gainupbplot.jpg')
plot(gainupb$N ~ gainupb$C,xlim=c(0,6),ylim=c(0,5),main="Location: Upland B, Category: Gain",xlab="Concentration of C",ylab="Concentration of N")
abline(gainupbfit)
dev.off()
print("Long/wet cor:")
print(cor(longwet$C,longwet$N))
longwetfit <- lm(longwet$N ~ longwet$C)
jpeg('/home/brendan/Desktop/images/plot/longwetplot.jpg')
plot(longwet$N ~ longwet$C,xlim=c(0,25),ylim=c(0,10),main="Location: Wetland, Category: Long",xlab="Concentration of C",ylab="Concentration of N")
abline(longwetfit)
dev.off()
print("Long/pond cor:")
print(cor(longpond$C,longpond$N))
longpondfit <- lm(longpond$N ~ longpond$C)
jpeg('/home/brendan/Desktop/images/plot/longpondplot.jpg')
plot(longpond$N ~ longpond$C,xlim=c(0,15),ylim=c(0,10),main="Location: Pond, Category: Long",xlab="Concentration of C",ylab="Concentration of N")
abline(longpondfit)
dev.off()
print("Long/upa cor:")
print(cor(longupa$C,longupa$N))
longupafit <- lm(longupa$N ~ longupa$C)
jpeg('/home/brendan/Desktop/images/plot/longupaplot.jpg')
plot(longupa$N ~ longupa$C,xlim=c(0,5),ylim=c(0,5),main="Location: Upland A, Category: Long",xlab="Concentration of C",ylab="Concentration of N")
abline(longupafit)
dev.off()
print("Long/upb cor:")
print(cor(longupb$C,longupb$N))
longupbfit <- lm(longupb$N ~ longupb$C)
jpeg('/home/brendan/Desktop/images/plot/longupbplot.jpg')
plot(longupb$N ~ longupb$C,xlim=c(0,5),ylim=c(0,5),main="Location: Upland B, Category: Long",xlab="Concentration of C",ylab="Concentration of N")
abline(longupbfit)
dev.off()
print("Lost/pond cor:")
print(cor(lostpond$C,lostpond$N))
lostpondfit <- lm(lostpond$N ~ lostpond$C, na.action=na.omit)
jpeg('/home/brendan/Desktop/images/plot/lostpondplot.jpg')
plot(lostpond$N ~ lostpond$C,xlim=c(0,10),ylim=c(0,5),main="Location: Pond, Category: Lost",xlab="Concentration of C",ylab="Concentration of N")
dev.off()
print("Lost/wet cor:")
print(cor(lostwet$C,lostwet$N))
lostwetfit <- lm(lostwet$N ~ lostwet$C)
jpeg('/home/brendan/Desktop/images/plot/lostwetplot.jpg')
plot(lostwet$N ~ lostwet$C,xlim=c(0,20),ylim=c(0,10),main="Location: Wet, Category: Lost",xlab="Concentration of C",ylab="Concentration of N")
abline(lostwetfit)
dev.off()
print("Lost/upa cor:")
print(cor(lostupa$C,lostupa$N))
lostupafit <- lm(lostupa$N ~ lostupa$C)
jpeg('/home/brendan/Desktop/images/plot/lostupaplot.jpg')
plot(lostupa$N ~ lostupa$C,xlim=c(0,2),ylim=c(0,2),main="Location: Upland A, Category: Lost",xlab="Concentration of C",ylab="Concentration of N")
abline(lostupafit)
dev.off()
print("Lost/upb cor:")
print(cor(lostupb$C,lostupb$N))
lostupbfit <- lm(lostupb$N ~ lostupb$C)
jpeg('/home/brendan/Desktop/images/plot/lostupbplot.jpg')
plot(lostupb$N ~ lostupb$C,xlim=c(0,10),ylim=c(0,5),main="Location: Upland B, Category: Lost",xlab="Concentration of C",ylab="Concentration of N")
abline(lostupbfit)
dev.off()
jpeg('/home/brendan/Desktop/images/resid/lostpondresid.jpg')
plot(lostpond$C,resid(lostpondfit), xlim=c(0,30), ylim=c(-2,2), ylab="Residuals", xlab = "Concentration of C", main = "Lost/Pond")
abline(0, 0)
dev.off()
jpeg('/home/brendan/Desktop/images/resid/lostwetresid.jpg')
plot(lostwet$C,resid(lostwetfit), xlim=c(0,30), ylim=c(-5,5), ylab="Residuals", xlab = "Concentration of C", main = "Lost/Wetland")
abline(0, 0)
dev.off()
jpeg('/home/brendan/Desktop/images/resid/lostuparesid.jpg')
plot(lostupa$C,resid(lostupafit), xlim=c(0,30), ylim=c(-2,2), ylab="Residuals", xlab = "Concentration of C", main = "Lost/Upland A")
abline(0, 0)
dev.off()
jpeg('/home/brendan/Desktop/images/resid/lostupbresid.jpg')
plot(lostupb$C,resid(lostupbfit), xlim=c(0,10), ylim=c(-2,2), ylab="Residuals", xlab = "Concentration of C", main = "Lost/Upland B")
abline(0, 0)
dev.off()
jpeg('/home/brendan/Desktop/images/resid/gainpondresid.jpg')
plot(gainpond$C,resid(gainpondfit), xlim=c(0,30), ylim=c(-2,2), ylab="Residuals", xlab = "Concentration of C", main = "Gain/Pond")
abline(0, 0)
dev.off()
jpeg('/home/brendan/Desktop/images/resid/gainwetresid.jpg')
plot(gainwet$C,resid(gainwetfit), xlim=c(0,30), ylim=c(-5,5), ylab="Residuals", xlab = "Concentration of C", main = "Gain/Wetland")
abline(0, 0)
dev.off()
jpeg('/home/brendan/Desktop/images/resid/gainuparesid.jpg')
plot(gainupa$C,resid(gainupafit), xlim=c(0,30), ylim=c(-2,2), ylab="Residuals", xlab = "Concentration of C", main = "Gain/Upland A")
abline(0, 0)
dev.off()
jpeg('/home/brendan/Desktop/images/resid/gainupbresid.jpg')
plot(gainupb$C,resid(gainupbfit), xlim=c(0,10), ylim=c(-2,2), ylab="Residuals", xlab = "Concentration of C", main = "Gain/Upland B")
abline(0, 0)
dev.off()
jpeg('/home/brendan/Desktop/images/resid/longpondresid.jpg')
plot(longpond$C,resid(longpondfit), xlim=c(0,30), ylim=c(-2,2), ylab="Residuals", xlab = "Concentration of C", main = "Long/Pond")
abline(0, 0)
dev.off()
jpeg('/home/brendan/Desktop/images/resid/longwetresid.jpg')
plot(longwet$C,resid(longwetfit), xlim=c(0,30), ylim=c(-5,5), ylab="Residuals", xlab = "Concentration of C", main = "Long/Wetland")
abline(0, 0)
dev.off()
jpeg('/home/brendan/Desktop/images/resid/longuparesid.jpg')
plot(longupa$C,resid(longupafit), xlim=c(0,30), ylim=c(-2,2), ylab="Residuals", xlab = "Concentration of C", main = "Long/Upland A")
abline(0, 0)
dev.off()
jpeg('/home/brendan/Desktop/images/resid/longupbresid.jpg')
plot(longupb$C,resid(longupbfit), xlim=c(0,10), ylim=c(-2,2), ylab="Residuals", xlab = "Concentration of C", main = "Long/Upland B")
abline(0, 0)
dev.off()
