data = read.csv("/home/brendan/Desktop/ass1.csv")
print(data)
lost <- data[which(data$Category=="Lost"),]
print(lost)
gain <- data[which(data$Category=="Gain"),]
print(gain)
long <- data[which(data$Category=="Long"),]
print(long)
longpond <- long[which(long$Sample=="Pond"),]
print(longpond)
longwet <- long[which(long$Sample=="Wetland"),]
print(longwet)
longupa <- long[which(long$Sample=="Upland A"),]
print(longupa)
longupb <- long[which(long$Sample=="Upland B"),]
print(longupb)
gainpond <- gain[which(gain$Sample=="Pond"),]
print(gainpond)
gainwet <- gain[which(gain$Sample=="Wetland"),]
print(gainwet)
gainupa <- gain[which(gain$Sample=="Upland A"),]
print(gainupa)
gainupb <- gain[which(gain$Sample=="Upland B"),]
print(gainupb)
lostpond <- lost[which(lost$Sample=="Pond"),]
print(lostpond)
lostwet <- lost[which(lost$Sample=="Wetland"),]
print(lostwet)
lostupa <- lost[which(lost$Sample=="Upland A"),]
print(lostupa)
lostupb <- lost[which(lost$Sample=="Upland B"),]
print(lostupb)
jpeg('/home/brendan/Desktop/images/longpond.jpg')
barplot(c(mean(longpond$C),mean(longpond$N)),main="Location: Pond, Category: Long",col=c("darkblue","red"),names.arg=c("C","N"),ylim=c(0,12))
dev.off()
jpeg('/home/brendan/Desktop/images/longwet.jpg')
barplot(c(mean(longwet$C),mean(longwet$N)),main="Location: Wetland, Category: Long",col=c("darkblue","red"),names.arg=c("C","N"),ylim=c(0,20))
dev.off()
jpeg('/home/brendan/Desktop/images/longupa.jpg')
barplot(c(mean(longupa$C),mean(longupa$N)),main="Location: Upland A, Category: Long",col=c("darkblue","red"),names.arg=c("C","N"),ylim=c(0,4))
dev.off()
jpeg('/home/brendan/Desktop/images/longupb.jpg')
barplot(c(mean(longupb$C),mean(longupb$N)),main="Location: Upland B, Category: Long",col=c("darkblue","red"),names.arg=c("C","N"),ylim=c(0,4))
dev.off()
jpeg('/home/brendan/Desktop/images/lostpond.jpg')
barplot(c(mean(lostpond$C),mean(lostpond$N)),main="Location: Pond, Category: Lost",col=c("darkblue","red"),names.arg=c("C","N"),ylim=c(0,12))
dev.off()
jpeg('/home/brendan/Desktop/images/lostwet.jpg')
barplot(c(mean(lostwet$C),mean(lostwet$N)),main="Location: Wetland, Category: Lost",col=c("darkblue","red"),names.arg=c("C","N"),ylim=c(0,15))
dev.off()
jpeg('/home/brendan/Desktop/images/lostupa.jpg')
barplot(c(mean(lostupa$C),mean(lostupa$N)),main="Location: Upland A, Category: Lost",col=c("darkblue","red"),names.arg=c("C","N"),ylim=c(0,2))
dev.off()
jpeg('/home/brendan/Desktop/images/lostupb.jpg')
barplot(c(mean(lostupb$C),mean(lostupb$N)),main="Location: Upland B, Category: Lost",col=c("darkblue","red"),names.arg=c("C","N"),ylim=c(0,6))
dev.off()
jpeg('/home/brendan/Desktop/images/gainpond.jpg')
barplot(c(mean(gainpond$C),mean(gainpond$N)),main="Location: Pond, Category: Gain",col=c("darkblue","red"),names.arg=c("C","N"),ylim=c(0,12))
dev.off()
jpeg('/home/brendan/Desktop/images/gainwet.jpg')
barplot(c(mean(gainwet$C),mean(gainwet$N)),main="Location: Wetland, Category: Gain",col=c("darkblue","red"),names.arg=c("C","N"),ylim=c(0,15))
dev.off()
jpeg('/home/brendan/Desktop/images/gainupa.jpg')
barplot(c(mean(gainupa$C),mean(gainupa$N)),main="Location: Upland A, Category: Gain",col=c("darkblue","red"),names.arg=c("C","N"),ylim=c(0,4))
dev.off()
jpeg('/home/brendan/Desktop/images/gainupb.jpg')
barplot(c(mean(gainupb$C),mean(gainupb$N)),main="Location: Upland B, Category: Gain",col=c("darkblue","red"),names.arg=c("C","N"),ylim=c(0,4))
dev.off()
pond <- data[which(data$Sample=="Pond"),]
print(lost)
wet <- data[which(data$Sample=="Wetland"),]
print(wet)
upa <- data[which(data$Sample=="Upland A"),]
print(upa)
upb <- data[which(data$Sample=="Upland B"),]
print(upb)
print("Pond C:")
print(summary(pond$C))
print("Pond N:")
print(summary(pond$N))
print("Wet C:")
print(summary(wet$C))
print("Wet N:")
print(summary(wet$N))
print("Upland A C:")
print(summary(upa$C))
print("Upland A N:")
print(summary(upa$N))
print("Upland B C:")
print(summary(upb$C))
print("Upland B N:")
print(summary(upb$N))
print("Lost C:")
print(summary(lost$C))
print("Lost N:")
print(summary(lost$N))
print("Gain C:")
print(summary(gain$C))
print("Gain N:")
print(summary(gain$N))
print("Long C:")
print(summary(long$C))
print("Long N:")
print(summary(long$N))
print("All C:")
allc <- data$C
print(allc)
print("All N:")
alln <- data$N
print(alln)
print("Gain/pond cor:")
print(cor(gainpond$C,gainpond$N))
gainpondfit <- lm(gainpond$N ~ gainpond$C)
jpeg('/home/brendan/Desktop/images/gainpondplot.jpg')
plot(gainpond$N ~ gainpond$C,xlim=c(0,15),ylim=c(0,10),main="Location: Pond, Category: Gain",xlab="Concentration of C",ylab="Concentration of N")
abline(gainpondfit)
dev.off()
print("Gain/wet cor:")
print(cor(gainwet$C,gainwet$N))
gainwetfit <- lm(gainwet$N ~ gainwet$C)
jpeg('/home/brendan/Desktop/images/gainwetplot.jpg')
plot(gainwet$N ~ gainwet$C,xlim=c(0,15),ylim=c(0,10),main="Location: Wetland, Category: Gain",xlab="Concentration of C",ylab="Concentration of N")
abline(gainwetfit)
dev.off()
